### ISSUE TITLE
Windows provisioning fails while trying to resolve IP

### ISSUE THREAD

**Issue by jarretlavallee** [oscar-stack/vagrant-hosts#75]
*Environment:* Vagrant 2.1, Ruby 2.4.4, Vagrant-hosts 2.8.2, macOS 10.13
*VM Version:* Windows 2012 R2 in Openstack

*Issue:*
When provisioning the machine, the hosts provider fails with the following error. 

~~~
/Users/<username>/.vagrant.d/gems/2.4.4/gems/vagrant-hosts-2.8.2/lib/vagrant-hosts/cap/facts/windows.rb:40:in `get_default_iface': Catched Error: undefined method `split' for nil:NilClass (NoMethodError)
        from /Users/jarret.lavallee/.vagrant.d/gems/2.4.4/gems/vagrant-hosts-2.8.2/lib/vagrant-hosts/cap/facts/windows.rb:13:in `load_facts'
        from /Users/jarret.lavallee/.vagrant.d/gems/2.4.4/gems/vagrant-hosts-2.8.2/lib/vagrant-hosts/cap/facts/base.rb:12:in `network_facts'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/capability_host.rb:111:in `call'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/capability_host.rb:111:in `capability'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/guest.rb:43:in `capability'
~~~

*What we think:*
The [sudo](https://github.com/oscar-stack/vagrant-hosts/blob/master/lib/vagrant-hosts/cap/facts/base.rb#L36) method chomps the stdout, which is stripping the new lines of the `netstat -rn` output. 

In the debug output we see the following hash from the command output has an `:stdout` element for each line. 

~~~
DEBUG winrmshell: Output: #<WinRM::Output:0x00000001027859f8 @data=[{:stdout=>"===========================================================================\r\n"}, {:stdout=>"Interface List\r\n"}, {:stdout=>" 12...fa 16 3e 57 dc df ......Red Hat VirtIO Ethernet Adapter\r\n"}, {:stdout=>"  1...........................Software Loopback Interface 1\r\n"}, {:stdout=>" 13...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter\r\n"}, {:stdout=>"===========================================================================\r\n"}, {:stdout=>"\r\n"}, {:stdout=>"IPv4 Route Table\r\n"}, {:stdout=>"===========================================================================\r\n"}, {:stdout=>"Active Routes:\r\n"}, {:stdout=>"Network Destination        Netmask          Gateway       Interface  Metric\r\n"}, {:stdout=>"          0.0.0.0          0.0.0.0      192.168.0.1     192.168.0.14      5\r\n"}, {:stdout=>"        127.0.0.0        255.0.0.0         On-link         127.0.0.1    306\r\n"}, {:stdout=>"        127.0.0.1  255.255.255.255         On-link         127.0.0.1    306\r\n"}, {:stdout=>"  127.255.255.255  255.255.255.255         On-link         127.0.0.1    306\r\n"}, {:stdout=>"  169.254.169.254  255.255.255.255      192.168.0.1     192.168.0.14      6\r\n"}, {:stdout=>"      192.168.0.0    255.255.255.0         On-link      192.168.0.14    261\r\n"}, {:stdout=>"     192.168.0.14  255.255.255.255         On-link      192.168.0.14    261\r\n"}, {:stdout=>"    192.168.0.255  255.255.255.255         On-link      192.168.0.14    261\r\n"}, {:stdout=>"        224.0.0.0        240.0.0.0         On-link         127.0.0.1    306\r\n"}, {:stdout=>"        224.0.0.0        240.0.0.0         On-link      192.168.0.14    261\r\n"}, {:stdout=>"  255.255.255.255  255.255.255.255         On-link         127.0.0.1    306\r\n"}, {:stdout=>"  255.255.255.255  255.255.255.255         On-link      192.168.0.14    261\r\n"}, {:stdout=>"===========================================================================\r\n"}, {:stdout=>"Persistent Routes:\r\n"}, {:stdout=>"  None\r\n"}, {:stdout=>"\r\n"}, {:stdout=>"IPv6 Route Table\r\n"}, {:stdout=>"===========================================================================\r\n"}, {:stdout=>"Active Routes:\r\n"}, {:stdout=>" If Metric Network Destination      Gateway\r\n"}, {:stdout=>"  1    306 ::1/128                  On-link\r\n"}, {:stdout=>" 12    261 fe80::/64                On-link\r\n"}, {:stdout=>" 12    261 fe80::711b:51ce:b373:5ebd/128\r\n"}, {:stdout=>"                                    On-link\r\n"}, {:stdout=>"  1    306 ff00::/8                 On-link\r\n"}, {:stdout=>" 12    261 ff00::/8                 On-link\r\n"}, {:stdout=>"===========================================================================\r\n"}, {:stdout=>"Persistent Routes:\r\n"}, {:stdout=>"  None\r\n"}], @exitcode=0>
ERROR warden: Error occurred: undefined method `split' for nil:NilClass
~~~

Printing the stdout from the `sudo` method results in a single lined string. 

~~~
===========================================================================Interface List 12...fa 16 3e 57 dc df ......Red Hat VirtIO Ethernet Adapter  1...................
........Software Loopback Interface 1 13...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter===========================================================================IPv4 R
oute Table===========================================================================Active Routes:Network Destination        Netmask          Gateway       Interface  Metr
ic          0.0.0.0          0.0.0.0      192.168.0.1     192.168.0.14      5        127.0.0.0        255.0.0.0         On-link         127.0.0.1    306        127.0.0.1  2
55.255.255.255         On-link         127.0.0.1    306  127.255.255.255  255.255.255.255         On-link         127.0.0.1    306  169.254.169.254  255.255.255.255      19
2.168.0.1     192.168.0.14      6      192.168.0.0    255.255.255.0         On-link      192.168.0.14    261     192.168.0.14  255.255.255.255         On-link      192.168.
0.14    261    192.168.0.255  255.255.255.255         On-link      192.168.0.14    261        224.0.0.0        240.0.0.0         On-link         127.0.0.1    306        224
.0.0.0        240.0.0.0         On-link      192.168.0.14    261  255.255.255.255  255.255.255.255         On-link         127.0.0.1    306  255.255.255.255  255.255.255.25
5         On-link      192.168.0.14    261===========================================================================Persistent Routes:  NoneIPv6 Route Table===============
============================================================Active Routes: If Metric Network Destination      Gateway  1    306 ::1/128                  On-link 12    261 f
e80::/64                On-link 12    261 fe80::711b:51ce:b373:5ebd/128                                    On-link  1    306 ff00::/8                 On-link 12    261 ff00
::/8                 On-link===========================================================================Persistent Routes:  None
~~~

*Potential fix:*
As it looks like a behavior change in vagrant or ruby with the newer versions, we could stop chomping the stdout to allow the windows fact logic to function. Base testing with `stdout << data` works with CentOS and Windows machines.

**Comment by Sharpie** [comment]
This turned out to be an issue in Vagrant 1.9+ as a result of the winrm gem upgrading from v1.8.1 to v2.2.3. WinRM 2.0 moved the implementation of Powershell over to using PSRP where it was previously running through a CMD.exe shell in 1.8. This is 10000% the right implementation, but it changed the way line breaks in command output are transported which caused this problem.

This has been fixed in oscar-stack/vagrant-hosts@427a72d and released in vagrant-hosts 2.8.3.
