### ISSUE TITLE
undefined method 'start_with?'

### ISSUE THREAD

**Issue by gprossliner** [oscar-stack/vagrant-hosts#80]
The plugin always worked as expected. Thank you very much for your work!

But after I destroyed all boxes (vagrant destroy -f), I'm not able to get them up again, with an exception from the vagrant-hosts plugin:

```
/home/USER/.vagrant.d/gems/2.4.4/gems/vagrant-hosts-2.9.0/lib/vagrant-hosts/addresses.rb:186:in `resolve_addresses': undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /home/USER/.vagrant.d/gems/2.4.4/gems/vagrant-hosts-2.9.0/lib/vagrant-hosts/addresses.rb:137:in `block in resolve_host_entries'
	from /home/USER/.vagrant.d/gems/2.4.4/gems/vagrant-hosts-2.9.0/lib/vagrant-hosts/addresses.rb:135:in `each'
	from /home/USER/.vagrant.d/gems/2.4.4/gems/vagrant-hosts-2.9.0/lib/vagrant-hosts/addresses.rb:135:in `flat_map'
	from /home/USER/.vagrant.d/gems/2.4.4/gems/vagrant-hosts-2.9.0/lib/vagrant-hosts/addresses.rb:135:in `resolve_host_entries'
	from /home/USER/.vagrant.d/gems/2.4.4/gems/vagrant-hosts-2.9.0/lib/vagrant-hosts/addresses.rb:34:in `all_hosts'
	from /home/USER/.vagrant.d/gems/2.4.4/gems/vagrant-hosts-2.9.0/lib/vagrant-hosts/cap/sync_hosts/posix.rb:34:in `format_hosts'
	from /home/USER/.vagrant.d/gems/2.4.4/gems/vagrant-hosts-2.9.0/lib/vagrant-hosts/cap/sync_hosts/posix.rb:11:in `update_hosts'
	from /home/USER/.vagrant.d/gems/2.4.4/gems/vagrant-hosts-2.9.0/lib/vagrant-hosts/cap/sync_hosts/base.rb:31:in `sync!'
	from /home/USER/.vagrant.d/gems/2.4.4/gems/vagrant-hosts-2.9.0/lib/vagrant-hosts/cap/sync_hosts/base.rb:11:in `sync_hosts'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/capability_host.rb:111:in `call'

```

I'm not aware that I've done something on my (Ubuntu 18.04.3 LTS) host that may cause this issue. Uninstalling and reinstalling the plugin doesn't change the behavior.

**Comment by gprossliner** [comment]
* Upgraded to Vagrant 2.2.6
* vagrant plugin repair
* vagrant plugin expunge

But it's still failing.

**Comment by gprossliner** [comment]
After digging into my own, and the plugins source, I found the problem. It was en error in the Vagrantfile. The problem was within this block, the p.add_host line:

```ruby
    config.vm.provision :hosts do |p|
        p.autoconfigure = true
        p.add_host ENV['K8S_APISERVER_VIP'], ["#{ENV['K8S_APISERVER_HOST']}}"]
    end
```

I'm using the vagrant-env plugin to load some configuration. If the  K8S_APISERVER_VIP Environment variable is not set, the 'address' argument of 'add_host' is nil.

This is not checked on calling add_host:
https://github.com/oscar-stack/vagrant-hosts/blob/master/lib/vagrant-hosts/config.rb#L63-L69.
But later on, on enumeration, basically get a nil deref issue.
